[project]
name = "intro-to-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ömer Yaslıtaş", email = "87611354+yaslitasomer@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "elasticsearch<9.0.0",
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=2.52.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.6.1",
    "sqlitesearch>=0.3.0",
]

[project.scripts]
intro-to-rag = "intro_to_rag:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
